site_name: Wirecard - AcceptSDK Partner Documentation

#- MDS-VOD:
#    - 'An Overview of Video on Demand': 'temp.md'

theme: 'material'
#theme_dir: 'mkdocs-material/material'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

#extra_css:
#  - 'stylesheets/acceptsdk.css'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://de.linkedin.com/in/martin-donath-20a95039'
  palette:
    primary: 'indigo'
    accent: 'red'
#  logo: 'images/logo.png'

# Page tree
pages:
  - Welcome!: index.md
  - Getting Started:
    - The Overall Architecture: overall-architecture.md
    - The SDK Architecture: sdk-architecture.md
    - Guide to Setting up Terminals: guide-setup-terminals.md
  - Integrating the SDK: integrating.md
  - iOS SDK Reference: ios-reference.md
  - Android SDK Reference:
    - Class Library:
      - AcceptBackendException: temp-test.md
      - AcceptCashDrawerExtension: temp.md
      - AcceptDevice: temp.md
      - AcceptException: temp.md
      - AcceptExtension: temp.md
      - AcceptPrinterExtension: temp.md
      - AcceptPublicExtension: temp.md
      - AcceptRetrofitListener: temp.md
      - AcceptScannerExtension: temp.md
      - AcceptSDK: temp.md
      - AcceptSdkBuilder: temp.md
      - AcceptSdkFactory: temp.md
    - Package Library:
      - de.wirecard.acceptsdk2: temp.md
      - de.wirecard.acceptsdk2.core.model.sale: temp.md
  - Additional References:
    - Glossary of Acronyms: glossary-acronyms.md
    - Glossary of Terminology: glossary-terminology.md
  - Appendices:
    - A - Switch Reference: appa-switch.md
    - B - EMV Transaction Flow: appb-emv.md
#    - C - Guide to Payment Processing (Both Platforms): appc-payment.md
